name: jhipsterapplication

services:
  mongodb:
    image: mongo:6.0.6
    command: ['--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/mongodb-keyfile']
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jhipsterapplication
      - MONGO_INITDB_ROOT_PASSWORD=jhipsterapplication
      - MONGO_INITDB_DATABASE=jhipsterapplication
    volumes:
      - mongodb_keys:/data
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://jhipsterapplication:jhipsterapplication@localhost:27017/admin --quiet
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:27018:27017
    init: true
    entrypoint: >
      sh -c "
        if [ ! -f /data/mongodb-keyfile ]; then
          openssl rand -base64 756 > /data/mongodb-keyfile &&
          chmod 400 /data/mongodb-keyfile &&
          chown 999:999 /data/mongodb-keyfile
        fi &&
        docker-entrypoint.sh mongod $$MONGO_EXTRA_ARGS --replSet rs0 --bind_ip_all --keyFile /data/mongodb-keyfile &
        sleep 10 &&
        mongosh mongodb://jhipsterapplication:jhipsterapplication@localhost:27017/admin --eval 'rs.initiate()' &&
        wait
      "

volumes:
  mongodb_keys:
  mongodb_data:
