# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipster
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
